version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL}
    container_name: listoxi-app
    restart: unless-stopped
    depends_on:
      - pocketbase

  pocketbase:
    build:
      context: .
      dockerfile: pocketbase.dockerfile
    container_name: listoxi-pb
    volumes:
      - pb_data:/pb/pb_data
    restart: unless-stopped

volumes:
  pb_data:
